---
project:
  type: website

format:
  html:
    theme: cyborg
  revealjs:
    auto-stretch: false
    callout-appearance: simple
    code-copy: true
    footer: "{{< meta title >}} - <https://lucascolley.github.io/talks>"
    hash-type: number
    history: false
    link-external-icon: true
    mermaid:
      theme: dark
    menu:
      hideMissingTitles: true
      useTextContentForMissingTitles: false
    preview-links: true
    slide-number: true
    theme: dark
    transition: none

website:
  navbar:
    title: <a href="https://lucascolley.github.io" class="navbar-brand">Lucas Colley</a>
    tools:
      - icon: github
        href: https://github.com/lucascolley/talks
  site-url: https://lucascolley.github.io/talks
  title: Lucas Colley
